ProyectoIngenieria/ProyectoIngenieria/Models/ViewModels/Usuarios/AgregarUsuariosViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ProyectoIngenieria.Models.ViewModels.Usuarios {
    public class AgregarUsuariosViewModel {
        [Required(ErrorMessage = "El nombre es requerido")]
        public string Nombre { get; set; }

        [DisplayName("Primer apellido")]
        [Required(ErrorMessage = "El primer apellido es requerido")]
        public string Apellido1 { get; set; }

        [DisplayName("Segundo apellido")]
        [Required(ErrorMessage = "El segundo apellido es requerido")]
        public string Apellido2 { get; set; }

        [DisplayName("Cédula de identidad")]
        [Required(ErrorMessage = "La cédula de identidad es requerida")]
        public string Cedula { get; set; }

        [DisplayName("Correo electrónico")]
        [Required(ErrorMessage = "El correo electrónico es requerido")]
        [EmailAddress(ErrorMessage = "Debe ingresar un correo válido")]
        public string Correo { get; set; }

        [DisplayName("Teléfono")]
        [Required(ErrorMessage = "El teléfono es requerido")]
        public string Telefono { get; set; }

        [DisplayName("Nombre de usuario")]
        [Required(ErrorMessage = "El nombre de usuario es requerido")]
        public string NombreUsuario { get; set; }

        [DisplayName("Tipo de usuario")]
        [Required(ErrorMessage = "Debe seleccionar un tipo de usuario")]
        public int TipoUsuario { get; set; }

        [DisplayName("Contraseña")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "La contraseña es requerida")]
        public string Contrasena { get; set; }

        [DisplayName("Confirmar contraseña")]
        [DataType(DataType.Password)]
        [Compare("Contrasena", ErrorMessage = "Las contraseñas no coinden")]
        public string ConfirmarContrasena { get; set; }
    }
}

ProyectoIngenieria/ProyectoIngenieria/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using ProyectoIngenieria.Models;
using ProyectoIngenieria.Models.EntityFramework;
using ProyectoIngenieria.Models.ViewModels;
using ProyectoIngenieria.Models.ViewModels.Ahorros;
using ProyectoIngenieria.Models.ViewModels.Creditos;

namespace ProyectoIngenieria.Controllers {
    /// <summary>
    /// Controlador para gestionar el inicio de sesiñon d eun usuario y sus opciones, ademas de la recuperación de contraseña
    /// </summary>
    public class UsuarioController : Controller {
        private ingenieriaso2020Entities ModeloBD;

        public UsuarioController() {
            // Instanciar modelo de la DB EF
            ModeloBD = new ingenieriaso2020Entities();
        }

        [HttpGet]
        public ActionResult Index() {
            if (!ValidarSiEstaLogueado()) { return RedirectToAction("InicioSesion"); }

            string TipoUsuario = Convert.ToString(Session["TipoUsuario"]);
            var Persona = (TBL_PERSONAS)Session["DatosPersona"];

            if (TipoUsuario.Equals("Cliente")) {
                var AhorrosClienteBD = ModeloBD.TBL_AHORROS_CLIENTE.Where(x => x.IdCliente == Persona.Id).ToList();
                IEnumerable<AhorrosClienteViewModel> AhorrosCliente = AhorrosClienteBD.Select(x => new AhorrosClienteViewModel(x)).ToList();
                ViewBag.Ahorros = AhorrosCliente;

                var CreditosClienteBD = ModeloBD.TBL_CREDITOS_CLIENTE.Where(x => x.IdCliente == Persona.Id).ToList();
                IEnumerable<CreditosClienteViewModel> CreditosCliente = CreditosClienteBD.Select(x => new CreditosClienteViewModel(x)).ToList();
                ViewBag.Creditos = CreditosCliente;
            }

            return View();
        }

        [HttpGet]
        public ActionResult InicioSesion() {
            if (ValidarSiEstaLogueado()) { return RedirectToAction("Index"); } else { return View(); }
        }

        [HttpPost]
        public ActionResult IniciarSesion(IniciarSesionViewModel Modelo) {
            var Usuario = ModeloBD.TBL_USUARIOS.Where(x => x.Nombre.Equals(Modelo.NombreUsuario) && x.Pass.Equals(Modelo.Contrasena)).FirstOrDefault();

            if (Usuario != null) {
                var TipoUsuario = ModeloBD.TBL_TIPOS_USUARIO.Where(x => x.Id == Usuario.IdTipoUsuario).FirstOrDefault();

                this.Session.Add("Logueado", true);
                this.Session.Add("TipoUsuario", TipoUsuario.Descripcion);

                var Persona = ModeloBD.TBL_PERSONAS.Where(x => x.Id == Usuario.IdPersona).FirstOrDefault();
                this.Session.Add("DatosUsuario", Usuario);
                this.Session.Add("DatosPersona", Persona);

                // Redireccionar a la pagina de inicio de usuario
                return RedirectToAction("Index");
            }
            else {
                ModelState.AddModelError("", "El usuario o contraseña son incorrectos.");
                return View("InicioSesion", Modelo);
            }
        }

        [HttpPost]
        public ActionResult CerrarSesion() {
            this.Session.Add("Logueado", false);
            this.Session.Add("TipoUsuario", null);

            this.Session.Add("DatosUsuario", null);
            this.Session.Add("DatosPersona", null);

            return View("InicioSesion");
        }

        public bool ValidarSiEstaLogueado() {
            bool UsuarioLogueado = Convert.ToBoolean(this.Session["Logueado"]);
            return UsuarioLogueado;
        }

        public ActionResult CambioPass() {
            return View();
        }

        //Consultamos el correo por medio del nombre de usuario
        [HttpPost]
        public ActionResult ConsultarCorreoPorUsuario(IniciarSesionViewModel ModeloVista) {
            #region VARIABLES
            string Mensaje = string.Empty;
            int filas = 0;
            string NuevoPass = string.Empty;
            string Receptor, Asunto, MensajeCorreo;
            #endregion
            try {
                //Consultmaos en la db los datos del usuario para enviar el SMS
                List<SP_RetornarCorreoPorUsuario_Result> DatosUsuario =
                    ModeloBD.SP_RetornarCorreoPorUsuario(ModeloVista.NombreUsuario).ToList();
                //Validamos que tengan datos de lo contrario es un usuario no registrado
                if (DatosUsuario.Count != 0) {
                    //Generamos la nueva contraseña
                    NuevoPass = GenerarPassword(10);
                    //Actualizamos la contraseña del usario
                    filas = ModeloBD.SP_ActualizarContraseña(DatosUsuario[0].Id, NuevoPass);

                    if (filas > 0) {
                        //Enviamos el correo
                        Receptor = DatosUsuario[0].Email;
                        Asunto = "Cambio de contraseña";
                        MensajeCorreo = "Se actualizó su contraseña, por motivos de seguridad no comparta con terceras personas su nueca contraseña, ahora dirijase a inicio de sesión para hacer uso de la plataforma,\n" +
                            "su nueva contraseña es: " + NuevoPass;
                        if (EnviarCorreoElectronico(Receptor, Asunto, MensajeCorreo).Equals("Exito")) {
                            Mensaje = "Exito";
                        }

                    }
                }
            }
            catch (Exception) {
                Mensaje = "Error";
            }

            return Json(new {
                resultado = Mensaje
            });
        }

        public string EnviarCorreoElectronico(string Receptor, string Asunto, string Mensaje) {
            string Estado = "Exito";
            try {
                /* VARIABLES */
                string Emisor = "pruebasuniversidad2020@gmail.com";
                string Contraseña = "1234yalpstHASFGbsdh";
                string Host = "smtp.gmail.com";
                int Puerto = 25;

                /* DATOS DEL CORREO */
                MailMessage Correo = new MailMessage();
                Correo.From = new MailAddress(Emisor);
                Correo.To.Add(Receptor);
                Correo.Subject = Asunto;
                Correo.Body = Mensaje;
                Correo.IsBodyHtml = true;
                Correo.Priority = MailPriority.Normal;
                /* DATOS DEL SMTP */
                SmtpClient smtp = new SmtpClient();
                smtp.Host = Host;
                smtp.Port = Puerto;
                smtp.EnableSsl = true;
                smtp.UseDefaultCredentials = true;
                smtp.Credentials = new System.Net.NetworkCredential(Emisor, Contraseña);
                smtp.Send(Correo);
            }
            catch (Exception error) {
                string m = error.Message;
            }
            return Estado;
        }

        public string GenerarPassword(int longitud) {
            string contraseña = string.Empty;
            string[] letras = { "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "ñ", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z",
                                "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"};
            Random EleccionAleatoria = new Random();

            for (int i = 0; i < longitud; i++) {
                int LetraAleatoria = EleccionAleatoria.Next(0, 100);
                int NumeroAleatorio = EleccionAleatoria.Next(0, 9);

                if (LetraAleatoria < letras.Length) {
                    contraseña += letras[LetraAleatoria];
                }
                else {
                    contraseña += NumeroAleatorio.ToString();
                }
            }
            return contraseña;
        }
    }
}

ProyectoIngenieria/ProyectoIngenieria/Controllers/UsuariosController.cs
using ProyectoIngenieria.Models.EntityFramework;
using ProyectoIngenieria.Models.ViewModels.Usuarios;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoIngenieria.Controllers {
    /// <summary>
    /// Controlador para gestionar los usuarios del sistema
    /// </summary>
    public class UsuariosController : Controller {
        private ingenieriaso2020Entities ModeloBD;

        public UsuariosController() {
            // Instanciar modelo de la DB EF
            ModeloBD = new ingenieriaso2020Entities();
        }

        [HttpGet]
        public ActionResult Index() {
            if (!ValidarSiEstaLogueado()) { return RedirectToAction("InicioSesion", "Usuario"); }

            var ListaUsuarios = ModeloBD.TBL_PERSONAS.ToList();
            var Modelo = ListaUsuarios.Select(x => new IndexUsuariosViewModel(x)).ToList();
            return View(Modelo);
        }

        [HttpGet]
        public ActionResult ConfirmacionDatosGuardados() {
            if (!ValidarSiEstaLogueado()) { return RedirectToAction("InicioSesion", "Usuario"); }

            return View();
        }

        [HttpGet]
        public ActionResult Agregar() {
            if (!ValidarSiEstaLogueado()) { return RedirectToAction("InicioSesion", "Usuario"); }

            CargarListaTiposUsuario();

            return View();
        }

        [HttpPost]
        public ActionResult Agregar(AgregarUsuariosViewModel modelo) {
            if (!ValidarSiEstaLogueado()) { return RedirectToAction("InicioSesion", "Usuario"); }

            if (!ModelState.IsValid) {
                ModelState.AddModelError("", "Error, el modelo no es válido");

                CargarListaTiposUsuario();

                return View(modelo);
            }

            var Persona = new TBL_PERSONAS();
            Persona.Cedula = modelo.Cedula;
            Persona.Nombre = modelo.Nombre;
            Persona.Apellido1 = modelo.Apellido1;
            Persona.Apellido2 = modelo.Apellido2;
            Persona.Email = modelo.Correo;
            Persona.Telefono1 = modelo.Telefono;

            var Usuario = new TBL_USUARIOS();
            Usuario.Nombre = modelo.NombreUsuario;
            Usuario.Pass = modelo.Contrasena;
            Usuario.Activo = true;
            Usuario.IdTipoUsuario = modelo.TipoUsuario;

            // Guardar en la base de datos la información de persona
            Persona = ModeloBD.TBL_PERSONAS.Add(Persona);
            var RegistrosAfectados = ModeloBD.SaveChanges();

            // Una vez que está guardado en la bd, se le asignó un Id a persona mediante Identity, tomar ese Id y 
            // colocarlo en la propiedad IdPersona del objeto usuario
            Usuario.IdPersona = Persona.Id;

            // Guardar en la base de datos la información de usuario
            Usuario = ModeloBD.TBL_USUARIOS.Add(Usuario);
            RegistrosAfectados = ModeloBD.SaveChanges();

            return RedirectToAction("ConfirmacionDatosGuardados");
        }

        [HttpGet]
        public ActionResult Editar(string id) {
            if (!ValidarSiEstaLogueado()) { return RedirectToAction("InicioSesion", "Usuario"); }

            if (string.IsNullOrEmpty(id)) {
                RedirectToAction("Index");
            }

            // TODO: Validar si el id es un numero mayor a 0

            int idUsuario = Convert.ToInt16(id);

            var usuarioBD = ModeloBD.TBL_USUARIOS.Where(x => x.Id == idUsuario).FirstOrDefault();

            EditarUsuariosViewModel modelo = new EditarUsuariosViewModel(usuarioBD);

            CargarListaTiposUsuario();

            return View(modelo);
        }

        [HttpPost]
        public ActionResult Editar(EditarUsuariosViewModel modelo) {
            if (!ValidarSiEstaLogueado()) { return RedirectToAction("InicioSesion", "Usuario"); }

            if (!ModelState.IsValid) {
                ModelState.AddModelError("", "Error, el modelo no es válido");

                CargarListaTiposUsuario();

                return View(modelo);
            }

            var usuarioBD = ModeloBD.TBL_USUARIOS.Where(x => x.Id == modelo.IdUsuario).FirstOrDefault();
            var personaBD = ModeloBD.TBL_PERSONAS.Where(x => x.Id == modelo.IdPersona).FirstOrDefault();

            // Datos de usuario
            usuarioBD.Nombre = modelo.NombreUsuario;
            usuarioBD.IdTipoUsuario = modelo.TipoUsuario;

            if (!string.IsNullOrEmpty(modelo.Contrasena)) {
                usuarioBD.Pass = modelo.Contrasena;
            }

            // Datos de persona
            personaBD.Nombre = modelo.Nombre;
            personaBD.Apellido1 = modelo.Apellido1;
            personaBD.Apellido2 = modelo.Apellido2;
            personaBD.Cedula = modelo.Cedula;
            personaBD.Email = modelo.Correo;
            personaBD.Telefono1 = modelo.Telefono;

            ModeloBD.Entry(usuarioBD).State = EntityState.Modified;
            ModeloBD.Entry(personaBD).State = EntityState.Modified;

            int RegistrosAfectados = ModeloBD.SaveChanges();

            return RedirectToAction("ConfirmacionDatosGuardados");
        }

        [HttpGet]
        public ActionResult Eliminar(string id) {
            if (!ValidarSiEstaLogueado()) { return RedirectToAction("InicioSesion", "Usuario"); }

            if (string.IsNullOrEmpty(id)) {
                RedirectToAction("Index");
            }

            // TODO: Validar si el id es un numero mayor a 0

            int idUsuario = Convert.ToInt16(id);

            var usuarioBD = ModeloBD.TBL_USUARIOS.Where(x => x.Id == idUsuario).FirstOrDefault();

            EditarUsuariosViewModel modelo = new EditarUsuariosViewModel(usuarioBD);

            return View(modelo);
        }

        [HttpPost, ActionName("Eliminar")]
        [ValidateAntiForgeryToken]
        public ActionResult EliminarConfirmado(int IdUsuario) {
            if (!ValidarSiEstaLogueado()) { return RedirectToAction("InicioSesion", "Usuario"); }

            var usuarioBD = ModeloBD.TBL_USUARIOS.Where(x => x.Id == IdUsuario).FirstOrDefault();
            var personaBD = ModeloBD.TBL_PERSONAS.Where(x => x.Id == usuarioBD.IdPersona).FirstOrDefault();

            ModeloBD.TBL_USUARIOS.Remove(usuarioBD);
            ModeloBD.TBL_PERSONAS.Remove(personaBD);

            int RegistrosAfectados = ModeloBD.SaveChanges();

            return RedirectToAction("Index");
        }

        private void CargarListaTiposUsuario() {
            // Obtener los tipos de usuario para enviarlo a la vista y llenar el select de tipos de usuario
            var TiposUsuario = ModeloBD.TBL_TIPOS_USUARIO.ToList();
            ViewBag.ListaTiposUsuario = TiposUsuario;
        }

        public bool ValidarSiEstaLogueado() {
            bool UsuarioLogueado = Convert.ToBoolean(this.Session["Logueado"]);
            return UsuarioLogueado;
        }
    }
}

ProyectoIngenieria/ProyectoIngenieria/Views/Usuario/CambioPass.cshtml
@{
    ViewBag.Title = "Cambio de contraseña!!";
}
<main id="main" style="margin-top: 5rem;">
    <div class="container">
        <div class="jumbotron">
            <h2><strong>@ViewBag.Title</strong></h2>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <form id="frmCambioPass" name="frmCambioPass" action="/" method="post" autocomplete="off">
                    <div class="form-group">
                        <label>Olvidé mi contraseña</label>
                        <input type="text" name="NombreUsuario" id="NombreUsuario" value="" placeholder="Ingrese el nombre del usuario" class="form-control" />
                    </div>
                    <div class="form-group">
                        <input type="button" name="btnEnviarCorreo" id="btnEnviarCorreo" value="Enviar" class="btn btn-outline-success form-control" />
                    </div>
                    
                </form>
            </div>
        </div>
        <div class="row">
            <p>Se enviara un correo electrónico con su nueva contraseña!!</p>
        </div>
    </div>


</main>
@Html.ValidationSummary(true)
@section Scripts{
    <script src="~/Scripts/JSGenerico.js"></script>
    <script src="~/Scripts/InicioSesion/InicioSesion.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
}

ProyectoIngenieria/ProyectoIngenieria/Views/Usuario/Index.cshtml
@using ProyectoIngenieria.Models.ViewModels.Ahorros;
@using ProyectoIngenieria.Models.ViewModels.Creditos;

@{
    ViewBag.Title = "Página de usuario";
    string Direccion = Url.Action("IniciarSesion", "Usuario");
    string TipoUsuario = Convert.ToString(Session["TipoUsuario"]);

    IEnumerable<AhorrosClienteViewModel> AhorrosCliente = ViewBag.Ahorros;
    IEnumerable<CreditosClienteViewModel> CreditosCliente = ViewBag.Creditos;
}

<main id="main" style="margin-top: 5rem;">
    <div class="container">

        @{
            if (TipoUsuario.Equals("Administrador")) {
                <h3>Bienvenido a las opciones de administrador</h3>

                <div class="jumbotron">
                    <a href="@Url.Action("Index", "Usuarios")" class="btn btn-outline-primary">Usuarios del sistema</a>
                    <a href="@Url.Action("Index", "Creditos")" class="btn btn-outline-success">Catálogo de créditos</a>
                    <a href="@Url.Action("Index", "Ahorros")" class="btn btn-outline-dark">Gestión de ahorros</a>
                </div>
            }
            else if (TipoUsuario.Equals("Colaborador")) {
                <h3>Bienvenido a las opciones de colaborador</h3>
            }
            else if (TipoUsuario.Equals("Cliente")) {
                <h3>Bienvenido a su perfil de cliente</h3>

                <div class="jumbotron">
                    <div class="row">
                        <div class="col-sm-12">
                            <h5>Sus ahorros</h5>

                            <table class="table table-responsive">
                                <tr>
                                    <th nowrap>
                                        @Html.DisplayNameFor(model => AhorrosCliente.FirstOrDefault().NombreAhorro)
                                    </th>
                                    <th nowrap>
                                        @Html.DisplayNameFor(model => AhorrosCliente.FirstOrDefault().Tasa)
                                    </th>
                                    <th nowrap>
                                        @Html.DisplayNameFor(model => AhorrosCliente.FirstOrDefault().Vencimiento)
                                    </th>
                                    <th nowrap>
                                        @Html.DisplayNameFor(model => AhorrosCliente.FirstOrDefault().AporteAcordado)
                                    </th>
                                    <th nowrap>
                                        @Html.DisplayNameFor(model => AhorrosCliente.FirstOrDefault().Saldo)
                                    </th>
                                    <th nowrap>
                                        @Html.DisplayNameFor(model => AhorrosCliente.FirstOrDefault().MontoUltimoAporte)
                                    </th>
                                    <th nowrap>
                                        @Html.DisplayNameFor(model => AhorrosCliente.FirstOrDefault().UltimoAporte)
                                    </th>
                                    <th nowrap>
                                        @Html.DisplayNameFor(model => AhorrosCliente.FirstOrDefault().Observaciones)
                                    </th>
                                    <th></th>
                                </tr>

                                @foreach (var item in AhorrosCliente) {
                                    <tr>
                                        <td nowrap>
                                            @Html.DisplayFor(modelItem => item.NombreAhorro)
                                        </td>
                                        <td nowrap>
                                            @Html.DisplayFor(modelItem => item.Tasa)
                                        </td>
                                        <td nowrap>
                                            @Html.DisplayFor(modelItem => item.Vencimiento)
                                        </td>
                                        <td nowrap>
                                            @Html.DisplayFor(modelItem => item.AporteAcordado)
                                        </td>
                                        <td nowrap>
                                            @Html.DisplayFor(modelItem => item.Saldo)
                                        </td>
                                        <td nowrap>
                                            @Html.DisplayFor(modelItem => item.MontoUltimoAporte)
                                        </td>
                                        <td nowrap>
                                            @Html.DisplayFor(modelItem => item.UltimoAporte)
                                        </td>
                                        <td nowrap>
                                            @Html.DisplayFor(modelItem => item.Observaciones)
                                        </td>
                                        <td nowrap>
                                            @Html.ActionLink("Pagos", "Pagos", "Creditos", new { id = item.Id })
                                        </td>
                                    </tr>
                                }
                            </table>
                        </div>
                    </div>
                </div>

                <div class="jumbotron">
                    <div class="row">
                        <div class="col-sm-12">
                            <h5>Sus créditos</h5>

                            <table class="table table-responsive">
                                <tr>
                                    <th nowrap>
                                        @Html.DisplayNameFor(model => CreditosCliente.FirstOrDefault().NombreCredito)
                                    </th>
                                    <th nowrap>
                                        @Html.DisplayNameFor(model => CreditosCliente.FirstOrDefault().Tasa)
                                    </th>
                                    <th nowrap>
                                        @Html.DisplayNameFor(model => CreditosCliente.FirstOrDefault().Monto)
                                    </th>
                                    <th nowrap>
                                        @Html.DisplayNameFor(model => CreditosCliente.FirstOrDefault().Plazo)
                                    </th>
                                    <th nowrap>
                                        @Html.DisplayNameFor(model => CreditosCliente.FirstOrDefault().Cuota)
                                    </th>
                                    <th nowrap>
                                        @Html.DisplayNameFor(model => CreditosCliente.FirstOrDefault().SaldoActual)
                                    </th>
                                    <th nowrap>
                                        @Html.DisplayNameFor(model => CreditosCliente.FirstOrDefault().PlazoRestante)
                                    </th>
                                    <th nowrap>
                                        @Html.DisplayNameFor(model => CreditosCliente.FirstOrDefault().MontoUltimoPago)
                                    </th>
                                    <th nowrap>
                                        @Html.DisplayNameFor(model => CreditosCliente.FirstOrDefault().UltimoPago)
                                    </th>
                                    <th nowrap>
                                        @Html.DisplayNameFor(model => CreditosCliente.FirstOrDefault().Observaciones)
                                    </th>
                                    <th></th>
                                </tr>

                                @foreach (var item in CreditosCliente) {
                                    <tr>
                                        <td nowrap>
                                            @Html.DisplayFor(modelItem => item.NombreCredito)
                                        </td>
                                        <td nowrap>
                                            @Html.DisplayFor(modelItem => item.Tasa)
                                        </td>
                                        <td nowrap>
                                            @Html.DisplayFor(modelItem => item.Monto)
                                        </td>
                                        <td nowrap>
                                            @Html.DisplayFor(modelItem => item.Plazo)
                                        </td>
                                        <td nowrap>
                                            @Html.DisplayFor(modelItem => item.Cuota)
                                        </td>
                                        <td nowrap>
                                            @Html.DisplayFor(modelItem => item.SaldoActual)
                                        </td>
                                        <td nowrap>
                                            @Html.DisplayFor(modelItem => item.PlazoRestante)
                                        </td>
                                        <td nowrap>
                                            @Html.DisplayFor(modelItem => item.MontoUltimoPago)
                                        </td>
                                        <td nowrap>
                                            @Html.DisplayFor(modelItem => item.UltimoPago)
                                        </td>
                                        <td nowrap>
                                            @Html.DisplayFor(modelItem => item.Observaciones)
                                        </td>
                                        <td nowrap>
                                            @Html.ActionLink("Aportes", "Aportes", "Ahorros", new { id = item.Id })
                                        </td>
                                    </tr>
                                }
                            </table>
                        </div>
                    </div>
                </div>
            }
            else {
                <h3>Bienvenido</h3>
            }
        }

        <div class="jumbotron">
            <form action="@Url.Action("CerrarSesion", "Usuario")" method="post">
                <input type="submit" value="Cerrar sesión" />
            </form>
        </div>
    </div>
</main>

<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />

ProyectoIngenieria/ProyectoIngenieria/Views/Usuario/InicioSesion.cshtml
@using ProyectoIngenieria.Models.ViewModels

@model IniciarSesionViewModel

@{
    ViewBag.Title = "Inicio sesión";
    string Direccion = Url.Action("IniciarSesion", "Usuario");
}

<main id="main" style="margin-top: 5rem;">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h3>Iniciar sesión</h3>
            </div>
            <div class="col-sm-12 col-md-4">
                <form id="IdInicioSesion" action="@Direccion" method="post" autocomplete="off">
                    <div class="form-group">
                        <label>Nombre de usuario</label>
                        <input type="text" name="NombreUsuario" id="NombreUsuario" value="" placeholder="Ingrese el nombre del usuario" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label>Contraseña</label>
                        <input type="password" name="Contrasena" id="Contrasena" value="" placeholder="Ingrese la contraseña" class="form-control" />
                    </div>
                    <div class="form-group">
                        <a href="~/Usuario/CambioPass">Cambiar contraseña</a>
                    </div>
                    <div class="form-group">
                        <input type="submit" id="btnIniciar" name="btnIniciar" value="Iniciar sesión" class="btn btn-success" />
                        <input type="reset" name="btnLimpiar" id="btnlimpiar" value="Limpiar formulario" class="btn btn-warning" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</main>

<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />

@Html.ValidationSummary(true)